## matriz A que tenga 300 x 300, con numeros aleatorios de 0 a mi numero de expediente

In [1]:
import numpy as np

In [6]:
matriz = np.random.randint(0, 223, (300, 300))

In [7]:
print(matriz)

[[  3  37  69 ...   8 121 118]
 [167  70 157 ... 166  18  45]
 [138 135  17 ...  42  84 139]
 ...
 [114 130 177 ... 190 180  98]
 [ 32  47  58 ...   9 129 168]
 [168  51  31 ... 156 195 164]]


## 2 forma

In [19]:
for i in range (300):
    for j in range(300):
        a=[i, j]

In [50]:
import random as rd

In [90]:
A = [[rd.randint(0,222) for i in range (fil_A)] for j in range(col_A)]

In [91]:
B = [[rd.randint(0,222) for i in range (fil_B)] for j in range(col_B)]

In [53]:
len(A)

10

In [101]:
A

[[204, 17, 133], [61, 165, 121], [188, 170, 135]]

In [45]:
len(B[0])

20

In [71]:
B

[[7, 107, 72, 77, 142, 110, 96, 2, 202, 207],
 [152, 170, 84, 21, 96, 2, 151, 48, 112, 53],
 [129, 81, 50, 205, 145, 178, 69, 157, 176, 30],
 [196, 60, 36, 71, 171, 79, 22, 14, 98, 57],
 [216, 195, 30, 15, 44, 27, 134, 43, 58, 113]]

In [55]:
if len(A[0]) == len(B):
    print("La matriz A es compatible con la matriz B")
else:
    print('Las matrices deben ser compatibles')

Las matrices deben ser compatibles


In [86]:
col_A = int(input('Ingrese las columnas de A :'))

Ingrese las columnas de A : 3


In [87]:
fil_A = int(input('Ingrese las filas de A :'))

Ingrese las filas de A : 3


In [88]:
col_B = int(input('Ingrese las columnas de B :'))

Ingrese las columnas de B : 3


In [89]:
fil_B = int(input('Ingrese las filas de A :'))

Ingrese las filas de A : 3


In [66]:
print("las dimensiones introducidas son A :", fil_A, col_A)

las dimensiones introducidas son A : 4 5


In [68]:
print("las dimensiones introducidas son B :", fil_B, col_B)

las dimensiones introducidas son B : 54 9


In [99]:
def mult_seq(A, B):
    m = len(A) 
    n = len(A[0])
    p = len(B[0])
    C = [[0 for _ in range(p)] for _ in range(m)]
    if len(B) != n:
        print("No es posible multiplicar estas matrices. Las dimensiones no son compatibles.")
        return None
        
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

In [100]:
mult_seq(A, B)

[[50345, 52433, 34010], [44459, 59194, 43179], [63363, 81082, 51458]]